tails, inits, initTails example implementation
snoyberg/mono-traversable pull request #214
Opened 2023-06-27 20:23 UTC by BebeSparkelSparkel

Here is my example implementation. I have only added:
- `tails`, `inits`, `initTails` to `class IsSequence`
- their default implementations
- added non-default implementations to the List instance

Can you review for correctness and then I will add it to the other instances?

I am unsure how to add this to tests. How should I add the tests?

closes #213

2023-07-02 05:38 UTC, snoyberg requested changes
Some test cases for this would be a nice addition if you don't mind. The code looks correct overall.

2023-07-16 21:20 UTC, BebeSparkelSparkel commented
I'll try to add some tests this week

2023-11-14 14:05 UTC, snoyberg approved these changes

2024-02-25 19:26 UTC, BebeSparkelSparkel commented
Added tests and fixed error for list instance.

Question: Should `initTails [] == [([],[])]` or `initTails == []`?

2024-02-26 12:59 UTC, snoyberg commented
I honestly have no idea, I've never used that function. Is there any prior art you're aware of for a definition?

2024-02-26 17:02 UTC, BebeSparkelSparkel commented
I have received comment from @tomjaguarpaw above and [Atijohn](https://www.reddit.com/r/haskell/comments/1b0ke0d/empty_case_for_new_function_inittails/).

Both recommend `initTails [] == [([], [])]`, as now implemented, with good reasoning.

So, this is ready to go.

2024-02-27 05:00 UTC, snoyberg commented on mono-traversable/src/Data/Sequences.hs
> +    -- @since ????
Once these are updated, I'll be happy to merge and release. Thanks!

2024-02-28 10:34 UTC, snoyberg approved these changes

2024-02-28 10:34 UTC, merged

2024-02-28 10:35 UTC, snoyberg commented
Thanks!